/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sonia
 */
public class sonia_carrion extends javax.swing.JFrame {
String ve[]={"1: prefiero hacer un mapa que explecar a alguen como puede llegar",
            "2: estoy enojado o enojada o contento o contenta exsactamente",
            "3: se docar o se toca  con instromiento musica",
            "4: asocio con estado con animo",
            "5: puedo  sumar  o puedo rapedez  ",
            "6: puedo ayudar un amigo a manejar sentemiento no puede los se  ",
            "7: le gusta trabajar  o calcular ",
            "8: aprendo a rapito un nuevo retmo",
            "9: no me es deficil decir  lo pienzo de un descocion de parte ",
            "10: desfruto de una buena charlas o descuido ",
            "11: siempre destengo norte de sur este donde este",
            "12: me gusta reoner grupo por de un fiesta de evento especial",
            "13: la vida parece vacia  sin musica ",
            "14: siempre entiente  los grafico en las instrucciones",
            "15: me gusta hacer rompe cabeza y juego electronicos",
            "16: me fue facil abrente andar viciclida o patenida",
            "17: me enojo cuando niego que aparece logica",
            "18: soy capas de convences a otros que segas otro planez",
            "19: tengo buen siento equelibrio de cordenacion ",
            "20: con frecuencia  vio configuracion mas facilitar que otros",
            "21: me gusta construyer modelos hacer culturas ",
            "22: tengo agudeza",
            "23: puedo merar objeto  de un manera con facilidad verbo",
            "24: con confrecuencia ago conecion alguien comento de m vida",
            "25: me gusta trabajar numero feguras",
            "26: le gusta centar selecccionamiente",
            "27: solo mera y estructura me ciento agosto",
            "28: me gusta selvar bolar  en la duchar",
            "29: son bueno para el aclitismo",
            "30: me gusta escriber cartas detallestas",
            "31: generalmente medoy cuenta",
            "32: me doy cuenta en la cara de  atra per",
            "33: me mentengo contacto de con cuesta edentefuicar los",
            "34: medoy  cuenta del animo del estado",
            "35: medoy cuenta bastante bien  pero otros piensan que me",
            ""};

int vec[]=new int[35];
int i=0;
    public sonia_carrion() {
        
        initComponents();
        preguntas.setText(ve[0]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        preguntas = new javax.swing.JTextArea();
        F = new javax.swing.JRadioButton();
        V = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 204));

        preguntas.setEditable(false);
        preguntas.setBackground(new java.awt.Color(255, 204, 204));
        preguntas.setColumns(20);
        preguntas.setRows(5);
        jScrollPane1.setViewportView(preguntas);

        F.setBackground(new java.awt.Color(255, 153, 204));
        grupo.add(F);
        F.setText("F");

        V.setBackground(new java.awt.Color(255, 153, 204));
        grupo.add(V);
        V.setText("V");

        jButton2.setBackground(new java.awt.Color(102, 255, 204));
        jButton2.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 0, 51));
        jButton2.setText("PRINCIPAL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(102, 255, 204));
        jButton1.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 0, 0));
        jButton1.setText("SEGUIENTE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("SONIA TERESA CARRION A.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 77, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(F)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(105, 105, 105)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(V)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(V)
                    .addComponent(F))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    if(i<=34){  
     if(V.isSelected()){
     vec[i]=1;
     }
     if(F.isSelected()){
       vec[i]=0;
    } 
     i++;  
     preguntas.setText(ve[i]); 
    }
    else{
    int re[]=new int[7];    
    re[0]=vec[8]+vec[9]+vec[16]+vec[21]+vec[29];
    re[1]=vec[4]+vec[6]+vec[14]+vec[19]+vec[24];
    re[2]=vec[0]+vec[10]+vec[13]+vec[22]+vec[26];
    re[3]=vec[7]+vec[15]+vec[18]+vec[20]+vec[28];
    re[4]=vec[2]+vec[3]+vec[12]+vec[23]+vec[27];
    re[5]=vec[1]+vec[5]+vec[25]+vec[30]+vec[32];
    re[6]=vec[11]+vec[17]+vec[31]+vec[33]+vec[34];
    int max=re[0];
    for(int h=0;h<7;h++){
    max=Math.max(max,re[0]);
    }
    String inte="Usted Tiene Una Clase De Inteligencia\n";
    for(int h=0;h<7;h++){
    if(max==re[h]){
    switch(h){
        case 0:inte=inte+" Inteligencia Linguistico ="+max+"\n"; break;
        case 1:inte=inte+" Inteligencia Matematico="+max+"\n";break;
        case 2:inte=inte+" Inteligencia Espacial="+max+"\n";break;
        case 3:inte=inte+" Inteligencia Corporal="+max+"\n";break;
        case 4:inte=inte+" Inteligencia Musical="+max+"\n";break;
        case 5:inte=inte+" Inteligencia Entra Personal="+max+"\n";break;
        case 6:inte=inte+" Inteligencia Enter Personal="+max+"\n";break;
    }    
    }
    }
    preguntas.setText("");
    preguntas.setText(inte); 
    }
    

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    i=0;
    preguntas.setText(ve[0]);


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sonia_carrion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sonia_carrion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sonia_carrion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sonia_carrion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sonia_carrion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton F;
    private javax.swing.JRadioButton V;
    private javax.swing.ButtonGroup grupo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea preguntas;
    // End of variables declaration//GEN-END:variables
}
